In [6]:
import pandas as pd

# Load the CSV files into pandas DataFrames
lat_lng_df = pd.read_csv('data/statedistrict_lat_lng.csv')
state_district_df = pd.read_csv('data/state_district.csv', index_col=0)

lat_lng_df.head()

,District,State_x,Dis_Latitude,Dis_Longitude
0,Anchorage School District,Alaska,61.246930,-149.688425
1,Ankeny Community School District,Iowa,42.934105,-94.682157
2,Birdville Independent School District,Texas,32.307856,-101.928432
3,Bixby Public Schools,Oklahoma,35.941919,-95.883104
4,Blount County Schools,Tennessee,35.682895,-83.920622

In [7]:
state_district_df.head()

,State,District,Origin_of_Challenge,Date_of_Challenge_or_Removal,Type_of_Ban,Author,Title
0,Alaska,Anchorage School District,Administrator,10/1/2021,Banned in Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir
1,Arkansas,Siloam Springs School District,Formal Challenge,1/1/2022,Banned in Libraries and Classrooms,"Kuklin, Susan",Beyond Magenta: Transgender Teens Speak Out
2,Florida,Brevard Public Schools,Administrator,5/1/2022,Banned Pending Investigation,"Maas, Sarah J.",A Court of Frost and Starlight (A Court of Tho...
3,Florida,Brevard Public Schools,Administrator,3/1/2022,Banned Pending Investigation,"Maas, Sarah J.",A Court of Mist and Fury (A Court of Thorns an...
4,Florida,Brevard Public Schools,Administrator,5/1/2022,Banned Pending Investigation,"Maas, Sarah J.",A ​Court of Silver Flames (A Court of Thorns a...

In [8]:
# Merging the DataFrames on the "District" column
merged_df = pd.merge(state_district_df, lat_lng_df[['District', 'Dis_Latitude', 'Dis_Longitude']], on="District", how="left")

# Display the first few rows of the merged DataFrame to verify the merge
merged_df.head()

,State,District,Origin_of_Challenge,Date_of_Challenge_or_Removal,Type_of_Ban,Author,Title,Dis_Latitude,Dis_Longitude
0,Alaska,Anchorage School District,Administrator,10/1/2021,Banned in Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,61.246930,-149.688425
1,Arkansas,Siloam Springs School District,Formal Challenge,1/1/2022,Banned in Libraries and Classrooms,"Kuklin, Susan",Beyond Magenta: Transgender Teens Speak Out,33.878898,-93.919538
2,Florida,Brevard Public Schools,Administrator,5/1/2022,Banned Pending Investigation,"Maas, Sarah J.",A Court of Frost and Starlight (A Court of Tho...,28.225497,-80.714725
3,Florida,Brevard Public Schools,Administrator,3/1/2022,Banned Pending Investigation,"Maas, Sarah J.",A Court of Mist and Fury (A Court of Thorns an...,28.225497,-80.714725
4,Florida,Brevard Public Schools,Administrator,5/1/2022,Banned Pending Investigation,"Maas, Sarah J.",A ​Court of Silver Flames (A Court of Thorns a...,28.225497,-80.714725

In [9]:
merged_df.to_json('data/coordinates.json', orient='records',force_ascii=False)