In [1]:
import pandas as pd
from pathlib import Path
import sqlite3
import os

In [2]:
path = Path("data/PEN America's Index of School Book Bans (July 1, 2021 - June 30, 2022).xlsx")
author_title_df = pd.read_excel(path, "Sorted by Author & Title")


author_title_df.head()

,Author,Title,Type of Ban,Secondary Author(s),Illustrator(s),Translator(s),State,District,Date of Challenge/Removal,Origin of Challenge,Latitude,Longitude
0,"Àbíké-Íyímídé, Faridah",Ace of Spades,Banned in Libraries and Classrooms,NaN,NaN,NaN,Florida,Indian River County School District,2021-11-01,Administrator,27.994402,-81.760254
1,"Acevedo, Elizabeth",Clap When You Land,Banned in Classrooms,NaN,NaN,NaN,Pennsylvania,Central York School District,2021-08-31,Administrator,41.203323,-77.194527
2,"Acevedo, Elizabeth",The Poet X,Banned in Libraries,NaN,NaN,NaN,Florida,Indian River County School District,2021-11-01,Administrator,27.994402,-81.760254
3,"Acevedo, Elizabeth",The Poet X,Banned in Libraries and Classrooms,NaN,NaN,NaN,New York,Marlboro Central School District,2022-02-01,Administrator,43.000000,-75.000000
4,"Acevedo, Elizabeth",The Poet X,Banned Pending Investigation,NaN,NaN,NaN,Texas,Fredericksburg Independent School District,2022-03-01,Administrator,31.000000,-100.000000

In [3]:
author_title_df.dtypes

Author                               object
Title                                object
Type of Ban                          object
Secondary Author(s)                  object
Illustrator(s)                       object
Translator(s)                        object
State                                object
District                             object
Date of Challenge/Removal    datetime64[ns]
Origin of Challenge                  object
Latitude                            float64
Longitude                           float64
dtype: object

In [4]:
author_title_df = author_title_df.fillna('')
author_title_df = author_title_df.loc[:, ['Author', 'Title', 'Type of Ban', 'State', 'District', 
                                          'Date of Challenge/Removal', 'Origin of Challenge', 'Latitude', 'Longitude' ]]

author_title_df= author_title_df.rename(columns={'Type of Ban':'Type_of_Ban',
                               'Date of Challenge/Removal': 'Date_of_Challenge_or_Removal',
                               'Origin of Challenge':'Origin_of_Challenge'})

In [5]:
author_title_df.head()

,Author,Title,Type_of_Ban,State,District,Date_of_Challenge_or_Removal,Origin_of_Challenge,Latitude,Longitude
0,"Àbíké-Íyímídé, Faridah",Ace of Spades,Banned in Libraries and Classrooms,Florida,Indian River County School District,2021-11-01,Administrator,27.994402,-81.760254
1,"Acevedo, Elizabeth",Clap When You Land,Banned in Classrooms,Pennsylvania,Central York School District,2021-08-31,Administrator,41.203323,-77.194527
2,"Acevedo, Elizabeth",The Poet X,Banned in Libraries,Florida,Indian River County School District,2021-11-01,Administrator,27.994402,-81.760254
3,"Acevedo, Elizabeth",The Poet X,Banned in Libraries and Classrooms,New York,Marlboro Central School District,2022-02-01,Administrator,43.000000,-75.000000
4,"Acevedo, Elizabeth",The Poet X,Banned Pending Investigation,Texas,Fredericksburg Independent School District,2022-03-01,Administrator,31.000000,-100.000000

In [6]:
author_title_df.to_json('data/author_title.json', orient='records', force_ascii=False)

In [7]:
state_district_df = pd.read_excel(path, "Sorted by State & District")
state_district_df = state_district_df.fillna('')
state_district_df.head()
state_district_df.dtypes
state_district_df = state_district_df.loc[:, ['State', 'District', 'Origin of Challenge','Date of Challenge/Removal',
                                              'Type of Ban', 'Author', 'Title', 
                                           'Latitude', 'Longitude' ]]

state_district_df= state_district_df.rename(columns={'Type of Ban':'Type_of_Ban',
                               'Date of Challenge/Removal': 'Date_of_Challenge_or_Removal',
                               'Origin of Challenge':'Origin_of_Challenge'})
state_district_df.head()

,State,District,Origin_of_Challenge,Date_of_Challenge_or_Removal,Type_of_Ban,Author,Title,Latitude,Longitude
0,Alaska,Anchorage School District,Administrator,2021-10-01,Banned in Libraries and Classrooms,"Kobabe, Maia",Gender Queer: A Memoir,66.160507,-153.369141
1,Arkansas,Siloam Springs School District,Formal Challenge,2022-01-01,Banned in Libraries and Classrooms,"Kuklin, Susan",Beyond Magenta: Transgender Teens Speak Out,34.799999,-92.199997
2,Florida,Brevard Public Schools,Administrator,2022-05-01,Banned Pending Investigation,"Maas, Sarah J.",A Court of Frost and Starlight (A Court of Tho...,27.994402,-81.760254
3,Florida,Brevard Public Schools,Administrator,2022-03-01,Banned Pending Investigation,"Maas, Sarah J.",A Court of Mist and Fury (A Court of Thorns an...,27.994402,-81.760254
4,Florida,Brevard Public Schools,Administrator,2022-05-01,Banned Pending Investigation,"Maas, Sarah J.",A ​Court of Silver Flames (A Court of Thorns a...,27.994402,-81.760254

In [8]:
state_district_df.to_json('data/state_district.json', orient='records',force_ascii=False)